version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=quarkus_test
  quinoa-todo:
    image: quarkus/quinoa-todo
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://db:5432/quarkus_test
      - QUARKUS_DATASOURCE_USERNAME=quarkus_test
      - QUARKUS_DATASOURCE_PASSWORD=quarkus_test
    depends_on:
      - db
    links:
      - db

